export type Alert = { id: number; customer_id: string; status: string; risk_score: number; created_at: string; updated_at: string; typology?: string; amount?: string; explanation?: string; rules?: { rule_code: string; weight: number; explanation: string; configuration?: string }[]; evidence?: { transaction_id: string }[]; evidenceCount?: number }
export type Customer = { id: string; first_name: string; last_name: string; country: string; kyc_status: string; risk_rating: string; politically_exposed: boolean }
export type Case = { id: number; customer_id: string; status: string; assigned_to: string | null; created_at: string; title?: string; alertIds?: number[] }
export type Rule = { code: string; enabled: boolean; threshold: number; secondaryThreshold: number; windowHours: number; minimumCount: number; weight: number }
const scenarios = [
 ['CUST_00001', 96, 'Structuring', '₹24,72,800', 'OPEN'], ['CUST_00002', 92, 'High-risk jurisdiction', '₹18,50,000', 'OPEN'], ['CUST_00003', 88, 'Rapid movement', '₹32,40,000', 'IN_REVIEW'], ['CUST_00004', 85, 'Behavioral deviation', '₹12,65,000', 'OPEN'], ['CUST_00005', 78, 'Threshold breach', '₹9,13,000', 'IN_REVIEW'], ['CUST_00006', 74, 'Round-number pattern', '₹8,30,000', 'OPEN'], ['CUST_00007', 68, 'Structuring', '₹22,82,500', 'OPEN'], ['CUST_00008', 62, 'Rapid movement', '₹16,60,000', 'CLEARED'], ['CUST_00009', 57, 'Behavioral deviation', '₹6,25,000', 'ESCALATED'], ['CUST_00010', 45, 'Threshold breach', '₹8,71,500', 'CLEARED'],
]
export const demoAlerts: Alert[] = scenarios.map((s, i) => ({ id: 1048 - i, customer_id: s[0] as string, risk_score: s[1] as number, typology: s[2] as string, amount: s[3] as string, status: s[4] as string, created_at: `2026-07-20T${String(10 - Math.floor(i / 3)).padStart(2, '0')}:${String(42 - i * 3).padStart(2, '0')}:00Z`, updated_at: '2026-07-20T10:42:00Z' }))
export const demoCustomers: Customer[] = ['K*** S***', 'A*** F***', 'R*** M***', 'P*** S***', 'A*** P***', 'S*** R***', 'N*** G***', 'V*** K***', 'M*** D***', 'D*** S***'].map((name, i) => ({ id: `CUST_${String(i + 1).padStart(5, '0')}`, first_name: name.split(' ')[0], last_name: name.split(' ')[1], country: 'IN', kyc_status: 'VERIFIED', risk_rating: i === 1 ? 'LOW' : i < 5 ? 'HIGH' : 'MEDIUM', politically_exposed: i === 3 }))
export const demoCases: Case[] = [{ id: 201, customer_id: 'CUST_00009', title: 'Unusual business account activity', status: 'IN_PROGRESS', assigned_to: 'analyst1', created_at: '2026-07-20T08:00:00Z', alertIds: [1040] }]
export const demoRules: Rule[] = ['THRESHOLD', 'STRUCTURING', 'RAPID_MOVEMENT', 'HIGH_RISK', 'BEHAVIORAL', 'ROUND_NUMBER'].map((code, i) => ({ code, enabled: true, threshold: [10000, 9000, 0.8, 0, 3, 1000][i], secondaryThreshold: i === 1 ? 9999 : 0, windowHours: i === 2 ? 48 : 24, minimumCount: i === 1 ? 3 : 1, weight: [20, 30, 25, 40, 15, 10][i] }))
export const ruleNames: Record<string, string> = { THRESHOLD: 'Threshold breach', STRUCTURING: 'Structuring', RAPID_MOVEMENT: 'Rapid movement', HIGH_RISK: 'High-risk jurisdiction', BEHAVIORAL: 'Behavioral deviation', ROUND_NUMBER: 'Round-number pattern' }
